# Generated by Django 4.0.4 on 2022-07-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_alter_user_options_user_wage_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wage',
            field=models.IntegerField(default=0, verbose_name='wage'),
        ),
    ]
