# Generated by Django 4.0.4 on 2023-02-26 10:39

from django.db import migrations, models
import sheets.models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_alter_user_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='SHEBA_number',
            field=models.CharField(blank=True, default='', max_length=26, verbose_name='SHEBA_number'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='account_number'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='bank_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_cert_changes_page',
            field=models.ImageField(blank=True, upload_to=sheets.models.user_directory_path, verbose_name='birth_cert_changes_page'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_cert_first_page',
            field=models.ImageField(blank=True, upload_to=sheets.models.user_directory_path, verbose_name='birth_cert_first_page'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='card_number'),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='emergency_phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='laptop_info',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='laptop_info'),
        ),
        migrations.AddField(
            model_name='user',
            name='military_service_card',
            field=models.ImageField(blank=True, upload_to=sheets.models.user_directory_path, verbose_name='military_service_card'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile1',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='mobile1'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile2',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='mobile2'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_ID',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='national_ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_ID_back_image',
            field=models.ImageField(blank=True, upload_to=sheets.models.user_directory_path, verbose_name='national_ID_back'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_ID_front_image',
            field=models.ImageField(blank=True, upload_to=sheets.models.user_directory_path, verbose_name='national_ID_front'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_image',
            field=models.ImageField(blank=True, upload_to=sheets.models.user_directory_path, verbose_name='personal_image'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_card',
            field=models.ImageField(blank=True, upload_to=sheets.models.user_directory_path, verbose_name='student_card'),
        ),
    ]
