# Generated by Django 4.0.4 on 2023-04-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addition1',
            field=models.IntegerField(default=0, verbose_name='addition'),
        ),
        migrations.AddField(
            model_name='user',
            name='fix_payment',
            field=models.IntegerField(default=0, verbose_name='fix_payment'),
        ),
        migrations.AddField(
            model_name='user',
            name='reduction1',
            field=models.IntegerField(default=0, verbose_name='reduction1'),
        ),
        migrations.AddField(
            model_name='user',
            name='reduction2',
            field=models.IntegerField(default=0, verbose_name='reduction2'),
        ),
        migrations.AddField(
            model_name='user',
            name='reduction3',
            field=models.IntegerField(default=0, verbose_name='reduction3'),
        ),
    ]
