# Generated by Django 4.0.4 on 2022-05-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_projectfamily_alter_sheet_user_project_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='mean',
            field=models.PositiveIntegerField(default=0, verbose_name='mean'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='total'),
        ),
    ]
