# Generated by Django 4.0.4 on 2023-04-10 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_user_addition1_user_fix_payment_user_reduction1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.TextField(default='', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
