# Generated by Django 4.0.4 on 2022-06-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_sheet_mean_sheet_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfamily',
            options={'verbose_name_plural': 'Projec Families'},
        ),
        migrations.AddField(
            model_name='sheet',
            name='submited',
            field=models.BooleanField(default=False, verbose_name='submitted'),
        ),
    ]
