# Generated by Django 4.0.4 on 2022-06-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0007_alter_projectfamily_options_sheet_submited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='submited',
            new_name='submitted',
        ),
    ]
