# Generated by Django 4.0.4 on 2023-04-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_remove_user_fix_payment_user_base_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='addition1',
            field=models.IntegerField(default=0, verbose_name='addition'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='base_payment',
            field=models.IntegerField(default=0, verbose_name='base_payment'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='reduction1',
            field=models.IntegerField(default=0, verbose_name='reduction1'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='reduction2',
            field=models.IntegerField(default=0, verbose_name='reduction2'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='reduction3',
            field=models.IntegerField(default=0, verbose_name='reduction3'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='wage',
            field=models.IntegerField(default=0, verbose_name='wage'),
        ),
    ]
