# Generated by Django 4.0.4 on 2024-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0010_alter_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='is_salary_paid',
            field=models.BooleanField(default=False, verbose_name='is_salary_paid'),
        ),
    ]
