# Generated by Django 4.0.4 on 2024-05-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0012_remove_sheet_is_salary_paid_sheet_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='addition2',
            field=models.IntegerField(default=0, verbose_name='addition2'),
        ),
        migrations.AddField(
            model_name='user',
            name='addition2',
            field=models.IntegerField(default=0, verbose_name='addition2'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Not paid'), (1, 'Only base paid'), (2, 'Only Complementary paid'), (3, 'Base+Complementary paid')], default=0, verbose_name='payment_status'),
        ),
    ]
