# Generated by Django 4.0.4 on 2024-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0013_sheet_addition2_user_addition2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Not Paid'), (1, 'Only Base Paid'), (2, 'Only Complementary Paid'), (3, 'Base+Complementary Paid'), (4, 'Refund Needed'), (5, 'Refund Paid')], default=0, verbose_name='payment_status'),
        ),
    ]
