# Generated by Django 4.0.4 on 2024-07-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0018_user_is_foodmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='food_reduction',
            field=models.IntegerField(default=0, verbose_name='food_reduction'),
        ),
        migrations.AddField(
            model_name='user',
            name='food_reduction',
            field=models.IntegerField(default=0, verbose_name='food_reduction'),
        ),
    ]
