# Generated by Django 4.0.4 on 2024-07-24 11:02

from django.db import migrations


def update_sheets(apps, schema_editor):
    Sheet = apps.get_model('sheets', 'Sheet')

    correct_weekdays = Sheet.empty_sheet_data(year=1403, month=5)
    correct_weekdays_dict = {entry['Day']: entry['WeekDay'] for entry in correct_weekdays}
    
    # Step 2: Update the week days in sheet.data
    for sheet in Sheet.objects.filter(year=1403, month=5):
        for entry in sheet.data:
            entry['WeekDay'] = correct_weekdays_dict[entry['Day']]

class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0020_food_data_order_mode'),
    ]

    operations = [
        migrations.RunPython(update_sheets),
    ]
