# Generated by Django 4.0.4 on 2024-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0021_auto_20240724_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_data',
            name='statistics_and_cost_data',
            field=models.JSONField(default=list),
        ),
    ]
