# Generated by Django 4.0.4 on 2024-09-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0022_food_data_statistics_and_cost_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='food_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
