# Generated by Django 4.0.4 on 2024-11-07 11:07

from django.db import migrations, models
import sheets.models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0024_alter_project_family_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_date',
        ),
        migrations.AddField(
            model_name='report',
            name='day',
            field=models.PositiveIntegerField(default=sheets.models.current_day, verbose_name='day'),
        ),
        migrations.AddField(
            model_name='report',
            name='month',
            field=models.PositiveIntegerField(default=sheets.models.current_month, verbose_name='month'),
        ),
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.PositiveIntegerField(default=sheets.models.current_year, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='main_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='sub_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
