# Generated by Django 4.0.4 on 2024-11-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0025_remove_report_report_date_report_day_report_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_MainReportManager',
            field=models.BooleanField(default=False, verbose_name='is_MainReportManager'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_SubReportManager',
            field=models.BooleanField(default=False, verbose_name='is_SubReportManager'),
        ),
    ]
