# Generated by Django 4.0.4 on 2024-11-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0026_user_is_mainreportmanager_user_is_subreportmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='manager_comment_hide_for_supervisor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='manager_comment_hide_for_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='supervisor_comment_hide_for_user',
            field=models.BooleanField(default=True),
        ),
    ]
