# Generated by Django 4.0.4 on 2024-11-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0027_report_manager_comment_hide_for_supervisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_limit_submission', models.BooleanField(default=False)),
            ],
        ),
    ]
