# Generated by Django 4.0.4 on 2024-11-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0028_dailyreportsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportsetting',
            name='end_report_hour',
            field=models.PositiveIntegerField(default=22, verbose_name='end_report_hour'),
        ),
        migrations.AddField(
            model_name='dailyreportsetting',
            name='start_report_hour',
            field=models.PositiveIntegerField(default=17, verbose_name='start_report_hour'),
        ),
    ]
