# Generated by Django 4.0.4 on 2025-01-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0029_dailyreportsetting_end_report_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name_p',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name persian'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_p',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name persian'),
        ),
    ]
