# Generated by Django 4.0.4 on 2025-08-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0030_user_first_name_p_user_last_name_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_financial_manager',
            field=models.BooleanField(default=False, verbose_name='is_financial_manager'),
        ),
    ]
