# Generated by Django 4.0.4 on 2025-08-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0031_user_is_financial_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_financial_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='is_FinancialManager',
            field=models.BooleanField(default=False, verbose_name='is_FinancialManager'),
        ),
    ]
