# Generated by Django 4.0.4 on 2025-08-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0032_remove_user_is_financial_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ProjectReportManager',
            field=models.BooleanField(default=False, verbose_name='is_ProjectReportManager'),
        ),
    ]
